<a href="https://colab.research.google.com/github/Rad-01code/ML-Projects/blob/main/Python_Libraries/Pandas_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

# **Section A: Creating DataFrames**

In [2]:
#  Create a DataFrame by hand from a dictionary with columns name, marks, and city for 4 students.
data = pd.DataFrame({
    'name' : ['Anuj','Khushi','Siya','Kiyaan'],
    'marks' : [59,78,90,85],
    'city' : ['Delhi','Noida','Gurugram','Meerut']
})

In [3]:
# Create a Series of 5 numbers with a custom index (for example, letters a to e), then get the element with label c.
nums = pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
nums['c']

np.int64(3)

In [4]:
# Save your hand-made DataFrame to a CSV with to_csv("students.csv", index=False), then read it back with read_csv. What happens if you leave out index=False? Try both and compare.
data.to_csv('students.csv',index=False)

In [5]:
datas=pd.read_csv('students.csv')
datas

     name  marks      city
0    Anuj     59     Delhi
1  Khushi     78     Noida
2    Siya     90  Gurugram
3  Kiyaan     85    Meerut

# **Section B: Inspecting the data**

In [6]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)

In [7]:
# Show the first 5 and last 3 rows.
print("First 5 rows : ")
print(df.head())
print("---------------------------------------------------------------")
print("Last 3 rows : ")
print(df.tail(3))

First 5 rows :
   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
---------------------------------------------------------------
Last 3 rows :
     total_bill   tip     sex smoker   day    time  size
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [8]:
# Print the shape, column names, and data types.
print("Shape of dataset : ",df.shape)
print("Column names : ",df.columns)
print("Data Types : \n",df.dtypes)

Shape of dataset :  (244, 7)
Column names :  Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')
Data Types :
 total_bill    float64
tip           float64
sex            object
smoker         object
day            object
time           object
size            int64
dtype: object

In [9]:
# Use df.info() and df.describe(). Which column has the highest mean, and which has the highest max?
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [10]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

total bill has the highest mean and highest max

In [11]:
# How many unique values does day have, and how many rows for each (value_counts)?
print(df['day'].unique())
print(df['day'].value_counts())

['Sun' 'Sat' 'Thur' 'Fri']
day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

### Note:
*   describe() only covers numeric columns. To include text columns too, use df.describe(include='all'), which adds count, unique, top, and freq for the categorical ones.
*   nunique() = count of distinct values; unique() = the values themselves.

# **Section C: Selecting columns and rows**

In [12]:
# Select just the tip column, first as a Series (df["tip"]) and then as a DataFrame (df[["tip"]]). Print the type of each.
print(type(df['tip']))
print(type(df[['tip']]))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

In [13]:
# Select the columns total_bill, tip, and size together.
print(df.loc[:,['tip','total_bill','size']])

      tip  total_bill  size
0    1.01       16.99     2
1    1.66       10.34     3
2    3.50       21.01     3
3    3.31       23.68     2
4    3.61       24.59     4
..    ...         ...   ...
239  5.92       29.03     3
240  2.00       27.18     2
241  2.00       22.67     2
242  1.75       17.82     2
243  3.00       18.78     2

[244 rows x 3 columns]

In [14]:
# Use iloc to get the first row, rows 5 to 9, and the element at row 3, column 2.
print("First row : \n",df.iloc[0])
print("-------------------------------------------------")
print("Rows  5 to 9 : \n",df.iloc[5:10])
print("-------------------------------------------------")
print("Row 3 col 2 element : ",df.iloc[3,2])

First row :
 total_bill     16.99
tip             1.01
sex           Female
smoker            No
day              Sun
time          Dinner
size               2
Name: 0, dtype: object
-------------------------------------------------
Rows  5 to 9 :
    total_bill   tip   sex smoker  day    time  size
5       25.29  4.71  Male     No  Sun  Dinner     4
6        8.77  2.00  Male     No  Sun  Dinner     2
7       26.88  3.12  Male     No  Sun  Dinner     4
8       15.04  1.96  Male     No  Sun  Dinner     2
9       14.78  3.23  Male     No  Sun  Dinner     2
-------------------------------------------------
Row 3 col 2 element :  Male

loc includes the end label; iloc excludes the end position

In [15]:
# Use loc to get rows 0 to 4 for only the columns total_bill and tip. Notice whether the end of the range is included, then compare with iloc[0:4].
print(df.loc[0:4,['total_bill','tip']])

   total_bill   tip
0       16.99  1.01
1       10.34  1.66
2       21.01  3.50
3       23.68  3.31
4       24.59  3.61

In [16]:
# Get every 10th row of the DataFrame using slicing.
print(df.iloc[::10])

     total_bill    tip     sex smoker   day    time  size
0         16.99   1.01  Female     No   Sun  Dinner     2
10        10.27   1.71    Male     No   Sun  Dinner     2
20        17.92   4.08    Male     No   Sat  Dinner     2
30         9.55   1.45    Male     No   Sat  Dinner     2
40        16.04   2.24    Male     No   Sat  Dinner     3
50        12.54   2.50    Male     No   Sun  Dinner     2
60        20.29   3.21    Male    Yes   Sat  Dinner     2
70        12.02   1.97    Male     No   Sat  Dinner     2
80        19.44   3.00    Male    Yes  Thur   Lunch     2
90        28.97   3.00    Male    Yes   Fri  Dinner     2
100       11.35   2.50  Female    Yes   Fri  Dinner     2
110       14.00   3.00    Male     No   Sat  Dinner     2
120       11.69   2.31    Male     No  Thur   Lunch     2
130       19.08   1.50    Male     No  Thur   Lunch     2
140       17.47   3.50  Female     No  Thur   Lunch     2
150       14.07   2.50    Male     No   Sun  Dinner     2
160       21.50   3.50    Male     No   Sun  Dinner     4
170       50.81  10.00    Male    Yes   Sat  Dinner     3
180       34.65   3.68    Male    Yes   Sun  Dinner     4
190       15.69   1.50    Male    Yes   Sun  Dinner     2
200       18.71   4.00    Male    Yes  Thur   Lunch     3
210       30.06   2.00    Male    Yes   Sat  Dinner     3
220       12.16   2.20    Male    Yes   Fri   Lunch     2
230       24.01   2.00    Male    Yes   Sat  Dinner     4
240       27.18   2.00  Female    Yes   Sat  Dinner     2

# **Section D: Filtering rows**

In [17]:
# Get all bills where total_bill is greater than 40.
df[df['total_bill']>40]

     total_bill    tip     sex smoker   day    time  size
59        48.27   6.73    Male     No   Sat  Dinner     4
95        40.17   4.73    Male    Yes   Fri  Dinner     4
102       44.30   2.50  Female    Yes   Sat  Dinner     3
142       41.19   5.00    Male     No  Thur   Lunch     5
156       48.17   5.00    Male     No   Sun  Dinner     6
170       50.81  10.00    Male    Yes   Sat  Dinner     3
182       45.35   3.50    Male    Yes   Sun  Dinner     3
184       40.55   3.00    Male    Yes   Sun  Dinner     2
197       43.11   5.00  Female    Yes  Thur   Lunch     4
212       48.33   9.00    Male     No   Sat  Dinner     4

In [18]:
#Get all Sunday bills (day == "Sun") for dinner (time == "Dinner") using &.
df[(df['day']=='Sun')& (df['time']=='Dinner')]

     total_bill   tip     sex smoker  day    time  size
0         16.99  1.01  Female     No  Sun  Dinner     2
1         10.34  1.66    Male     No  Sun  Dinner     3
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
186       20.90  3.50  Female    Yes  Sun  Dinner     3
187       30.46  2.00    Male    Yes  Sun  Dinner     5
188       18.15  3.50  Female    Yes  Sun  Dinner     3
189       23.10  4.00    Male    Yes  Sun  Dinner     3
190       15.69  1.50    Male    Yes  Sun  Dinner     2

[76 rows x 7 columns]

In [19]:
# Get rows where day is Sat or Sun, first using |, then using .isin(["Sat", "Sun"]).
df[(df['day']=='Sun') | (df['day']=='Sat')]

     total_bill   tip     sex smoker  day    time  size
0         16.99  1.01  Female     No  Sun  Dinner     2
1         10.34  1.66    Male     No  Sun  Dinner     3
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
238       35.83  4.67  Female     No  Sat  Dinner     3
239       29.03  5.92    Male     No  Sat  Dinner     3
240       27.18  2.00  Female    Yes  Sat  Dinner     2
241       22.67  2.00    Male    Yes  Sat  Dinner     2
242       17.82  1.75    Male     No  Sat  Dinner     2

[163 rows x 7 columns]

In [20]:
df[df['day'].isin(['Sat','Sun'])]

     total_bill   tip     sex smoker  day    time  size
0         16.99  1.01  Female     No  Sun  Dinner     2
1         10.34  1.66    Male     No  Sun  Dinner     3
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
238       35.83  4.67  Female     No  Sat  Dinner     3
239       29.03  5.92    Male     No  Sat  Dinner     3
240       27.18  2.00  Female    Yes  Sat  Dinner     2
241       22.67  2.00    Male    Yes  Sat  Dinner     2
242       17.82  1.75    Male     No  Sat  Dinner     2

[163 rows x 7 columns]

In [21]:
# Get bills for smokers where the tip was above 5, and show only total_bill, tip, and day (combine a filter with loc).
ans = df[(df['smoker']=='Yes') &  (df['tip']>5)].loc[:,['total_bill','tip','day']]
print(ans)

     total_bill    tip  day
170       50.81  10.00  Sat
172        7.25   5.15  Sun
181       23.33   5.65  Sun
183       23.17   6.50  Sun
211       25.89   5.16  Sat
214       28.17   6.50  Sat

In [22]:
# How many rows are in your answer to question 16? Which method gives you that number (len or shape)?
print(len(ans))

6

# **Section E : Mini Challenges**

In [23]:
# New column: create tip_pct = tip / total_bill * 100. Find the row with the highest tip percentage (idxmax).
df['tip_pct']=df['tip']/df['total_bill'] * 100
df.head()

   total_bill   tip     sex smoker  day    time  size    tip_pct
0       16.99  1.01  Female     No  Sun  Dinner     2   5.944673
1       10.34  1.66    Male     No  Sun  Dinner     3  16.054159
2       21.01  3.50    Male     No  Sun  Dinner     3  16.658734
3       23.68  3.31    Male     No  Sun  Dinner     2  13.978041
4       24.59  3.61  Female     No  Sun  Dinner     4  14.680765

In [24]:
df.loc[df['tip_pct'].idxmax()]

total_bill         7.25
tip                5.15
sex                Male
smoker              Yes
day                 Sun
time             Dinner
size                  2
tip_pct       71.034483
Name: 172, dtype: object

idxmax  gives index of max value

In [25]:
# Tidy view: show the 10 largest bills with only the columns total_bill, tip, tip_pct, and day (try sort_values).
sorted_bill = df.sort_values(by='total_bill',ascending=False)
sorted_bill.head(10)

     total_bill    tip     sex smoker   day    time  size    tip_pct
170       50.81  10.00    Male    Yes   Sat  Dinner     3  19.681165
212       48.33   9.00    Male     No   Sat  Dinner     4  18.621974
59        48.27   6.73    Male     No   Sat  Dinner     4  13.942407
156       48.17   5.00    Male     No   Sun  Dinner     6  10.379905
182       45.35   3.50    Male    Yes   Sun  Dinner     3   7.717751
102       44.30   2.50  Female    Yes   Sat  Dinner     3   5.643341
197       43.11   5.00  Female    Yes  Thur   Lunch     4  11.598237
142       41.19   5.00    Male     No  Thur   Lunch     5  12.138869
184       40.55   3.00    Male    Yes   Sun  Dinner     2   7.398274
95        40.17   4.73    Male    Yes   Fri  Dinner     4  11.774956

After sort_values, index labels stay with their rows, so use head() or iloc for the top N, not loc[0:N]

Important :
1. Get the 2 rows with the LARGEST 'Score'
top_scores = df.nlargest(2, columns='Score')

2. Get the 2 rows with the SMALLEST 'Age'
youngest = df.nsmallest(2, columns='Age')